// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABbpMe5l3x91VGv2uum2NPc7ANlzZQnz0',
    appId: '1:896016602477:web:466d4c8a1c573ee0527664',
    messagingSenderId: '896016602477',
    projectId: 'traveller-65d99',
    authDomain: 'traveller-65d99.firebaseapp.com',
    storageBucket: 'traveller-65d99.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmU8YrIQOAEPKXpN6EwXWy0O1UloK8mgE',
    appId: '1:896016602477:android:b730c8e54ff62b0b527664',
    messagingSenderId: '896016602477',
    projectId: 'traveller-65d99',
    storageBucket: 'traveller-65d99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgKOZ7k2rIHqnkg1VROZTQZSPbDbjd_bo',
    appId: '1:896016602477:ios:9e6789a782084afe527664',
    messagingSenderId: '896016602477',
    projectId: 'traveller-65d99',
    storageBucket: 'traveller-65d99.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgKOZ7k2rIHqnkg1VROZTQZSPbDbjd_bo',
    appId: '1:896016602477:ios:9e6789a782084afe527664',
    messagingSenderId: '896016602477',
    projectId: 'traveller-65d99',
    storageBucket: 'traveller-65d99.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );
}
